### PR TITLE
Add more debug logging

### PR DESCRIPTION
**Pull request by stenver**

### CODE REVIEW

**Comment by urmastalimaa** [comment]
This information has been present, at some point it was removed. @indrekj do you remember?

**Comment by stenver** [comment]
I am adding it at the moment to debug the operator authenticator in the CI

Specifically the failure to log in

**Comment by stenver** [comment]
I'm happy to remove it later, if the debug log is a problem for some reason

**Comment by stenver** [comment]
Should I bump the version too?

**Comment by indrekj** [comment]
Use branch. Lets not merge and bump the version immediately. I remember there was quite a lot of spam with all this (even for debug mode).

**Comment by stenver** [comment]
Ok, in this case the PR doesn't really need to get merged. I will just make the op auth to use this branch

**Comment by stenver** [comment]
The debug logs seemed ok. What are we going to do with this?

**Comment by indrekj** [comment]
It looks like we removed this in freddy so we can put it back here

**Comment by indrekj** [comment]
+1

**Comment by stenver** [comment]
Updated

**Pull request merged**
